services:
  nginx:
    build:
      context: ./
      dockerfile: Dockerfile
      target: nginx
    ports:
      - "8080:80"
  php_fpm:
    build: .
    build:
      context: ./
      dockerfile: Dockerfile
      target: fpm
    environment:
      - MOMENTO_AUTH_TOKEN=${MOMENTO_AUTH_TOKEN}
      - MONENTO_SESSION_CACHE_TTL=60
    network_mode: service:nginx
    