services:
  nginx:
    build:
      context: ./
      dockerfile: Dockerfile
      target: nginx
    ports:
      - "8080:80"
  php_fpm:
    build: .
    build:
      context: ./
      dockerfile: Dockerfile
      target: fpm
    environment:
      - MOMENTO_AUTH_TOKEN=${MOMENTO_AUTH_TOKEN}
      - MOMENTO_SESSION_TTL=120
    network_mode: service:nginx
    